# Generated by Django 2.2.2 on 2019-06-17 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_remove_project_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.ImageField(default='Project1.jpg', upload_to='profile_pics'),
        ),
    ]
